language: node_js
node_js:
- '4.4'
- '6.1'
deploy:
  provider: npm
  email: sebastian@urbantalk.se
  api_key:
    secure: Eunqe2bZS9BNuRHa8ddrMp88V1yb04tVniORdR+sCLi94XwxPA/FrZ+9E3zlW+mDAWBnz4I1EUcPaSFPm9c2AvzsNcU90GnO4FcXF0Ao2jeLtEWQUydMIb+z8JaV9pnfaAeKmFmORYk3u+q0fVdAtkesV8XV101vJlua6Ju+L7jk+cs2yhtA1S0LdzFnr2NhXlFPErtjc+1qgR9TDRDVPYZrw7hsTCBvqY9XVcWgqvRPLoSxZV9jTDS58jFjpGE6z2woBVoDLu358dRsdGt73osh7Q0UdX8AlOK4PCoS1B1dTVJU2VZG2FpDsN9q39yR6L8BVAYZIfT3iw1Zcr7plgXgUUqR1bXSPg9a8g400a+p627IFSfzo5Wu+GGY2r3u9mdRuWTk+r5lNCcDS4PSew+pZ+bFKVqPstbCwGaKsaUzhlu8ZK7o0ZxdGZ6uIHr3BE/pGSVa98ge5HqWYjOnp3yygYKyEL+neTQCV0ahOSEeE9uwV0oOtSfsFJWF+ZMEgdYQHxE6/8hL9qciCc/w8BEWeyIGF06jI2SgzoF83aBQrU80mp6zb6QzXLm1+ly01O+9UYftA2tuXDzD1QR1pdSpuc500przSPizYteYEHBCaQF84/ZcGn5hcP4BtfHah1JvmRKlbn/C7R48saFmn1AF1uUOva2MaShNC74XDG8=
  on:
    tags: true
    repo: jhsware/isomorphic-schema
