language: node_js
node_js:
- '4.4'
- '6.1'
deploy:
  provider: npm
  email: sebastian@urbantalk.se
  api_key:
    secure: kYnsjlu1LdsWQ4pfCkkeTZuEXKRuQ4ArnORQmtr8kEiE4rt1WoeYbdA0okQGOGzb0+jc6QgwGjGYoLZZQa23fsIQB9hm0fHx6c2lTmjs3QCn8I2F1bfJrNSLK9hlfQiItVfOSOR2a30rk70pmm1AiT8PGbUScnATy40SEMHUs9YZrE9ssk/VTyYqsPjgJpHJeZru+nsZRIwzKUFIoXvSFx5961w8+H9CBJQ4Oal8KB+FPBaBGen5BzFEeKGNnj2JLYcVyalHHjL6besLb7Htz774LA/bArF3NBz2cEq+fSXlpESieHtQ3T8UT8BO9JOIymDQaI8rK8eMZ+jo/e7SLkgQArDlXK8hmxbhUtKpWMgnIKaG+q+MzwrAka4C9e/tIYjTjStIe12p7bBiyok7Nm3H2yXzV2cPdQutB3ubP9W3EJyi5jXwblg5PEmTFYo6is+0Qu769AcULTI1qcDIgp6QQyTTI3M1ZL458nsLnavXlDHr6qaXyJ9MczpBdTKpwP93r4kuiG3JuZcYFsclB0bFfvKTZBnQ13qtTlhNUxAavuXxA06bBXs5opwU/2hXM3c88YSvF3R9ERfNEkdMfGW3MEuaPSBEUiSMu1VPlE+dZRunfCf//KcC+DXgQHeoa3ZoDHzOXH/GLUpcSmHK8BDI9gfXFLyF5pRHA6rBATE=
  on:
    tags: true
    repo: jhsware/isomorphic-schema
